FROM mbentley/django-uwsgi-nginx

MAINTAINER Diederik Hattingh <diederikjhattingh@gmail.com>

#Untested:
RUN pip install -r /opt/django/app/requirements.txt
RUN apt-get install python-imaging
RUN apt-get install tesseract-ocr