baseurl = "http://onlythefax.io/"
languageCode = "en-us"
title = "Only The Fax OTF"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Diederik_ZA"
	description = "Fax master"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "OTF"

		[params.navigation.links]
			about     = "About Us"
			what      = "What even is this"
            useful    = "Useful?"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Only The Fax"
		subtitle   = "Future of the Fax: Browse the Internet"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got your contemporary fax needs covered!"
		description = "We are bringing faxes into the next century. You can now easily browse the Internet with your standard fax machine."
		buttonText  = "Get started!"


	# Service section
	[params.what]
		headline = "What even is this?"
 
        bio1 = "Wait, did you say fax?  YES! FAX THE INTERNET! (NOTE: Beta!)"
        bio2 = "Simply print out in clear legable font (60pt+) the URL you want to browse, and send it to 012 3456789 ((012) TODO TODO) and you will shortly thereafter receive a [webkit](https://webkit.org/) renderd version of that website.  Simple and clean."

        [[params.what.list]]
            icon = "fa-fax"
            title = "Faxy mc fax face"
            description = "You fax us, and we fax you the Internet!"

        [[params.what.list]]
			icon = "fa-paper-plane"
			title = "Quick"
			description = "Quick and easy!"

		[[params.what.list]]
            icon = "fa-newspaper-o"
            title = "Easy"
            description = "Did we mention it was easy?"

    [params.money]
		    headline = "How does payment for this service work?"

            m1 = "For the beta, we are going to try a honesty payment system. If you like this service, and or found it amusing. Please send 1 earth dollar per page or part thereof."
            m2 = "Our service providers has informed us that \"love\" isn't an accepted form of payment to keep our business running."

    [params.bestResults]
            headline = "Follow these tips for best fax results"

            b1 = "Since the service relies heavily on magical unicorn powered OCR please follow these guidelines for best Internet fax results."
            b2 = "Good example:"
            img = "img/IMG_20160309_094705_r.jpg"

    [[params.bestResults.list]]
            item = "Always start URL with http or `https://` or `http://`"
    [[params.bestResults.list]]
            item = "Use a large font. White space is removed so, if your URL wraps it will still work."
    [[params.bestResults.list]]
            item = "No underlining of URLs."
    [[params.bestResults.list]]
            item = "Avoid trailing `/` at end of URL"

            
# TODO example


[params.futurePlans]
            headline = "What about v2.0?"

            f1 = "We have big ideas for the next release.  Circling a link with your pen, and sending the fax again, will follow a link.  Form entry for text fields (please don't send any passwords yet).  YouTube flip book support. And many many more exciting ideas."
            

    [params.useful]
		    headline = "Why not build something useful?"

            u1 = "Why build something useful when you can build something unbelievable?"
            u2 = "This service was built with the help of people that build things that are very useful (and used by people) most days of the week. Some have described them as [quite a good](http://www.thefieldoffice.co.za/) company to work for.  They take their work seriously, but know how to party as well. Ain't no party like a fax party! [Eeee ooooooowwwowwowow](https://www.dialupsound.com/)!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"
